<template>

  <div class="loveBox">
    <span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
     <span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
      <span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
       <span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
        <span class="Love1">Love</span><span class="text-3xl p-2">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
         <span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
          <span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span>
           <span class="text-3xl p-2">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love">Love</span><span class="Love1">Love</span><span class="Love">Love</span><span class="Love">Love</span>
  </div>
</template>

<script>
export default {};
</script>

<style>

</style>